#!/bin/bash

mkdir -p /new-drive/openstack/latest

cp /controller-install.sh /new-drive/openstack/latest
cp /worker-install.sh /new-drive/openstack/latest
cp /setup-controller-node.sh /new-drive/openstack/latest

chmod 755 /new-drive/openstack/latest/setup-controller-node.sh
chmod 755 /new-drive/openstack/latest/controller-install.sh
chmod 755 /new-drive/openstack/latest/worker-install.sh

cp -r /config-drive/* /new-drive/openstack/latest/

USERDATAVARS='$NAME:$ADVERTISE_CLIENT_URLS:$INITIAL_ADVERTISE_PEER_URLS:$TOKEN:$LISTEN_PEER_URLS:$LISTEN_CLIENT_URLS:$SSHKEY:$HOSTNAME'

if [ -f /config-drive/user_data ]
then
    echo "using user supplied user_data"
    envsubst "$USERDATAVARS" < /config-drive/user_data > /new-drive/openstack/latest/user_data
else
    echo "using user_data template"
    envsubst "$USERDATAVARS" < /user_data > /new-drive/openstack/latest/user_data
fi

cat /new-drive/openstack/latest/user_data

mkisofs -R -V config-2 -input-charset utf-8 -o "/iso/config-drive.iso" /new-drive
