#!/bin/bash

mkdir -p /new-drive/openstack/latest

#Copy static bits for setting up kubernetes
cp /controller-install.sh /new-drive/openstack/latest
cp /worker-install.sh /new-drive/openstack/latest
cp /setup-node.sh /new-drive/openstack/latest

chmod 755 /new-drive/openstack/latest/setup-node.sh
chmod 755 /new-drive/openstack/latest/controller-install.sh
chmod 755 /new-drive/openstack/latest/worker-install.sh

#If from stdin, read into /config-drive
if [ "$FROM_STDIN" = "false" ]
then
    echo "Reading config-drive from /config-drive. Set FROM_STDIN environment variable to read config tarball."
else
    (cd /config-drive ; tar -xf -)
fi

cp -r /config-drive/* /new-drive/openstack/latest/

#Source any env files.
NODE_ENV=/config-drive/$1.env
source $NODE_ENV

if [ -f /config-drive/user_data ]
then
    eval "echo \"$(cat /config-drive/user_data)\"" > /new-drive/openstack/latest/user_data
else
    eval "echo \"$(cat /user_data)\"" > /new-drive/openstack/latest/user_data
fi


#maybe tar and send to stdout
if [ "$CAT_TO_STDOUT" = "false" ]
then
    mkisofs -R -V config-2 -input-charset utf-8 -o "/iso/$NAME.iso" /new-drive
    echo "Wrote config-drive to /iso/$NAME. Set CAT_TO_STDOUT environment variable to output the iso to stdout."
else
    mkisofs -R -V config-2 -input-charset utf-8 /new-drive
fi
